const{ Schema, model} = require('mongoose');

const UserSchema = new Schema({
    names: {type: String, required: true},
    lastnames: {type: String, required: true},
    documentType: {type: String, required: true},
    idUser: {type: Number, required: true},
    password: {type: String, required: true},
    code: {type: Number, required: true},
    birthdate: {type: Date, required: true},
    genre: {type: String, required: true},
    phone: {type: Number, required: true},
    mail: {type: String, required: true},
    eps: {type: String, required: true},
    rh: {type: String, required: true},
    arl: String,
    allergy: {type: Boolean, required: true},
    allergyAns: String,
    nameParent: {type: String, required: true},
    phoneParent: {type: String, required: true},
    parent: {type: String, required: true},
    question1: {type: Boolean, required: true},
    question1Ans: String,
    question2: {type: Boolean, required: true},
    question2Ans: String,
    question3: {type: Boolean, required: true},
    question3Ans: String,
    question4: {type: Boolean, required: true},
    question4Ans: String,
    question5: {type: Boolean, required: true},
    question5Ans: String,
    question6: {type: Boolean, required: true},
    question7: {type: Boolean, required: true},
    question8: {type: Boolean, required: true},
    question9: {type: Boolean, required: true},
    question10: {type: Boolean, required: true},
    medicines: String,
    indicatedDose: String,
    question11: {type: Boolean, required: true},
    question11Ans: String,
    question12: {type: Boolean, required: true},
    question12Ans: String,
    timeWeek: Number,
    hours: Number,
    minutes: Number,
    lastTime: {type: String, required: true},
    health: Boolean,
    conditioning: Boolean,
    lose: Boolean,
    recreation: Boolean,
    increasedMuscle: Boolean,
    sports: Boolean
}, {
    timestamps: true
});

module.exports = model('User', UserSchema);